### ISSUE TITLE
Add more info to common/fs error messages

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zoc#121]
```
thread '<main>' panicked at 'Can`t open file', ../src/libcore/option.rs:330
```

**Comment by ozkriff** [comment]
```
$ rm assets/DroidSerif-Regular.ttf
$ ./target/release/zoc 
GL_VERSION: 3.0 Mesa 11.0.2
GLSL_VERSION: 1.30
GL_VENDOR: Intel Open Source Technology Center
GL_RENDERER: Mesa DRI Intel(R) Ivybridge Mobile 
thread '<main>' panicked at 'Can`t open file 'assets/DroidSerif-Regular.ttf' (No such file or directory (os error 2))', src/common/src/fs.rs:16
$ 
```
