### ISSUE TITLE
invalid filter method (253)

### ISSUE THREAD

**Issue by reverendhomer** [ozkriff/zoc#270]
Arch Linux, xmonad. This is clean `cargo build` + `cargo run` build. 
```
ecko@alpha in ~/develop/rust/zoc (master u=)
λ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/zoc`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FormatError("invalid filter method (253)")', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: zoc::texture::load_texture
             at ./src/texture.rs:13
  12: zoc::mesh_manager::load_object_mesh
             at ./src/mesh_manager.rs:102
  13: zoc::mesh_manager::MeshIdManager::new
             at ./src/mesh_manager.rs:62
  14: zoc::tactical_screen::TacticalScreen::new
             at ./src/tactical_screen.rs:286
  15: zoc::main_menu_screen::MainMenuScreen::handle_event_button_press
             at ./src/main_menu_screen.rs:87
  16: zoc::main_menu_screen::MainMenuScreen::handle_event_lmb_release
             at ./src/main_menu_screen.rs:70
  17: <zoc::main_menu_screen::MainMenuScreen as zoc::screen::Screen>::handle_event
             at ./src/main_menu_screen.rs:131
  18: zoc::visualizer::Visualizer::handle_events
             at ./src/visualizer.rs:89
  19: zoc::visualizer::Visualizer::tick
             at ./src/visualizer.rs:54
  20: zoc::main
             at ./src/main.rs:54
  21: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
  22: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  23: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  24: main
  25: __libc_start_main
  26: _start

```

```
ecko@alpha in ~/develop/rust/zoc (master u=)
λ cargo --version
cargo 0.18.0 (fe7b0cdcf 2017-04-24)
ecko@alpha in ~/develop/rust/zoc (master u=)
λ rustc --version
rustc 1.17.0 (56124baa9 2017-04-24)

```

**Comment by reverendhomer** [comment]
The problem was in assets. After `git pull` and `git checkout -- .` it is gone.
